export const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED'
export const PRODUCT_LIST_SUCCESSFUL = 'PRODUCT_LIST_SUCCESSFUL'
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE'

export const PRODUCT_DETAILS_REQUESTED = 'PRODUCT_DETAILS_REQUESTED'
export const PRODUCT_DETAILS_SUCCESSFUL = 'PRODUCT_DETAILS_SUCCESSFUL'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'
