export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED'
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT_OCCURRENCE = 'USER_LOGOUT_OCCURRENCE'

export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESSFUL = 'USER_REGISTRATION_SUCCESSFUL'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'
