export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED'
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT_OCCURRENCE = 'USER_LOGOUT_OCCURRENCE'

export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESSFUL = 'USER_REGISTRATION_SUCCESSFUL'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'

export const USER_UPDATEDPROFILE_REQUESTED = 'USER_UPDATEDPROFILE_REQUESTED'
export const USER_UPDATEDPROFILE_SUCCESSFUL = 'USER_UPDATEDPROFILE_SUCCESSFUL'
export const USER_UPDATEDPROFILE_FAILED = 'USER_UPDATEDPROFILE_FAILED'

export const USER_FINALUPDATEDPROFILE_REQUESTED =
  'USER_FINALUPDATEDPROFILE_REQUESTED'
export const USER_FINALUPDATEDPROFILE_SUCCESSFUL =
  'USER_FINALUPDATEDPROFILE_SUCCESSFUL'
export const USER_FINALUPDATEDPROFILE_FAILED = 'USER_FINALUPDATEDPROFILE_FAILED'
export const USER_FINALUPDATEDPROFILE_RESET = 'USER_FINALUPDATEDPROFILE_RESET'
