export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED'
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT_OCCURRENCE = 'USER_LOGOUT_OCCURRENCE'

export const USER_REGISTRATION_REQUESTED = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESSFUL = 'USER_REGISTRATION_SUCCESSFUL'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'

export const USER_DETAILPROFILE_REQUESTED = 'USER_DETAILPROFILE_REQUESTED'
export const USER_DETAILPROFILE_SUCCESSFUL = 'USER_DETAILPROFILE_SUCCESSFUL'
export const USER_DETAILPROFILE_FAILED = 'USER_DETAILPROFILE_FAILED'

export const USER_UPDATEDPROFILE_REQUESTED = 'USER_UPDATEDPROFILE_REQUESTED'
export const USER_UPDATEDPROFILE_SUCCESSFUL = 'USER_UPDATEDPROFILE_SUCCESSFUL'
export const USER_UPDATEDPROFILE_FAILED = 'USER_UPDATEDPROFILE_FAILED'
export const USER_UPDATEDPROFILE_RESET = 'USER_UPDATEDPROFILE_RESET'
